export const LOGIN_ROUTE = "/login"
export const SIGNUP_ROUTE = "/signup"
export const HOME_ROUTE = "/"
export const LOCKERS_ROUTE = "/lockers"
export const DASHBOARD_ROUTE = "/admin"
export const PROFILE_ROUTE = "/profile"